### ISSUE TITLE
Close button size incorrect

### ISSUE THREAD

**Issue by julabear** [GetAlluo/decentralised-app#10]
**Describe the bug**
Close button on withdraw / deposit / modal element on app.alluo.finance implemented incorrectly. 
1. "x" is not correct, 
2. size is not correct (it should be in line with the network label next to it) 

Screenshot of implementation
<img width="746" alt="image" src="https://user-images.githubusercontent.com/113053775/188965108-53ef2139-79eb-4533-bfce-7821ccbd3784.png">

**Expected behavior**
[here is the design](https://www.figma.com/file/qolBcysoPahA8ITvf6zeGG/Alluo---alluo.finance-website?node-id=5998%3A31904)

Should look like this
<img width="634" alt="image" src="https://user-images.githubusercontent.com/113053775/188964887-26f38f77-60e9-4bb7-85fd-042dd9beba23.png">

**Comment by abhisheknaiidu** [comment]
@0xtuytuy is anyone working on this? I would like to pick this.
