### ISSUE TITLE
Spacing and height on rows on farming tables

### ISSUE THREAD

**Issue by julabear** [GetAlluo/decentralised-app#7]
**Describe the bug**
- Table rows on app.alluo.finance have not been implemented with correct padding / height. 
- Please check fonts sizes in rows against designs

See the screenshot below that shows design on the left and implementation to the right, with red lines to show comparisons. 

<img width="961" alt="image" src="https://user-images.githubusercontent.com/113053775/188954291-6d341339-9f8b-4c34-ac12-710d4253929b.png">

**Expected behavior**
View correct design [here:](https://www.figma.com/file/qolBcysoPahA8ITvf6zeGG/Alluo---alluo.finance-website?node-id=5954%3A42265)

**Comment by hrishibhattu** [comment]
I'll work on this.
