### ISSUE TITLE
Implementation of design of modal on farming deposit / withdrawal / stake / transfer pages is not correct

### ISSUE THREAD

**Issue by julabear** [GetAlluo/decentralised-app#8]
**Describe the bug**
The implementation of design of modal on farming deposit / withdrawal pages is not correct.
(Also on stake, transfer and buy pages) 

- Button incorrect size (height / padding)
- Spacing between elements is not correct
- Margins on modal are incorrect

<img width="520" alt="image" src="https://user-images.githubusercontent.com/113053775/188959176-b8b4cd4b-600f-4be1-bf4d-eccc26939b53.png">

**Expected behaviour**
Design should be as per this this screen: [https://www.figma.com/file/qolBcysoPahA8ITvf6zeGG/Alluo---alluo.finance-website?node-id=5998%3A31904](url)
Note: designs must follows visual design, do not change content. 
Spacing on modals and between rows should be implemented on deposit / withdrawal, stake, buy and transfer pages

**Comment by abhisheknaiidu** [comment]
@0xtuytuy is anyone working on this? I would like to pick this.

**Comment by Dan1618** [comment]
@abhisheknaiidu 
I have already submitted the task

**Comment by Dan1618** [comment]
@julabear @0xtuytuy This is how it looks now, still paddings in Infos ("projected weekly earnings", "APY") dont look perfectly, but changing them would affect other parts of app -- same component is used in transfer and buy tab. Do you want me to make a workround or make it affects other the tabs or create another task for that? Also the blue switch button on/off would require a separte connected task.

![image](https://user-images.githubusercontent.com/17969092/192287694-975c8560-89f6-4621-babd-6e8bbb235b65.png)
