### ISSUE TITLE
Correct detail / add stroke to selector element on deposit / withdrawal screen in farms

### ISSUE THREAD

**Issue by julabear** [GetAlluo/decentralised-app#9]
**Describe the bug**

Selector is not implemented according to design on page: http://app.alluo.finance/farm/0
- Missing stroke surrounding whole element
- Please check font size + corner radius
- Check background colour

View comparison of implenetation (top) vs design (bottom) in screenshot below

<img width="741" alt="image" src="https://user-images.githubusercontent.com/113053775/188962588-67c54dbe-baa8-4572-804d-0a42e1e37480.png">

**Expected behaviour**

Correct design [here](https://www.figma.com/file/qolBcysoPahA8ITvf6zeGG/Alluo---alluo.finance-website?node-id=5998%3A31904): 

Close-up screenshot to show detail
<img width="749" alt="image" src="https://user-images.githubusercontent.com/113053775/188963069-9b30516d-bb37-4955-988b-694749a2403f.png">
<img width="955" alt="image" src="https://user-images.githubusercontent.com/113053775/188963117-ad8877d5-9a02-464c-bd43-ceb2199100bf.png">

**Comment by abhisheknaiidu** [comment]
@0xtuytuy is anyone working on this? I would like to pick this.
